// <auto-generated />
using Catalog.PersistenceDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.PersistenceDatabase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210922022707_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatalogDomain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Product 1",
                            Name = "Product 1",
                            Price = 561m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Product 2",
                            Name = "Product 2",
                            Price = 737m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Product 3",
                            Name = "Product 3",
                            Price = 212m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Product 4",
                            Name = "Product 4",
                            Price = 486m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Product 5",
                            Name = "Product 5",
                            Price = 397m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Product 6",
                            Name = "Product 6",
                            Price = 598m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Product 7",
                            Name = "Product 7",
                            Price = 595m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Product 8",
                            Name = "Product 8",
                            Price = 402m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Product 9",
                            Name = "Product 9",
                            Price = 185m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Product 10",
                            Name = "Product 10",
                            Price = 362m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Product 11",
                            Name = "Product 11",
                            Price = 589m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Product 12",
                            Name = "Product 12",
                            Price = 356m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Product 13",
                            Name = "Product 13",
                            Price = 476m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Product 14",
                            Name = "Product 14",
                            Price = 299m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Product 15",
                            Name = "Product 15",
                            Price = 377m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Product 16",
                            Name = "Product 16",
                            Price = 678m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Product 17",
                            Name = "Product 17",
                            Price = 649m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Product 18",
                            Name = "Product 18",
                            Price = 556m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Product 19",
                            Name = "Product 19",
                            Price = 689m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Product 20",
                            Name = "Product 20",
                            Price = 240m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Product 21",
                            Name = "Product 21",
                            Price = 498m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Product 22",
                            Name = "Product 22",
                            Price = 387m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Product 23",
                            Name = "Product 23",
                            Price = 862m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Product 24",
                            Name = "Product 24",
                            Price = 178m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Product 25",
                            Name = "Product 25",
                            Price = 182m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Product 26",
                            Name = "Product 26",
                            Price = 331m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Product 27",
                            Name = "Product 27",
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Product 28",
                            Name = "Product 28",
                            Price = 339m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Product 29",
                            Name = "Product 29",
                            Price = 962m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Product 30",
                            Name = "Product 30",
                            Price = 131m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Product 31",
                            Name = "Product 31",
                            Price = 456m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Product 32",
                            Name = "Product 32",
                            Price = 584m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Product 33",
                            Name = "Product 33",
                            Price = 407m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Product 34",
                            Name = "Product 34",
                            Price = 124m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Product 35",
                            Name = "Product 35",
                            Price = 647m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Product 36",
                            Name = "Product 36",
                            Price = 459m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Product 37",
                            Name = "Product 37",
                            Price = 423m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Product 38",
                            Name = "Product 38",
                            Price = 688m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Product 39",
                            Name = "Product 39",
                            Price = 254m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Product 40",
                            Name = "Product 40",
                            Price = 343m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Product 41",
                            Name = "Product 41",
                            Price = 327m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Product 42",
                            Name = "Product 42",
                            Price = 329m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Product 43",
                            Name = "Product 43",
                            Price = 649m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Product 44",
                            Name = "Product 44",
                            Price = 864m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Product 45",
                            Name = "Product 45",
                            Price = 809m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Product 46",
                            Name = "Product 46",
                            Price = 423m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Product 47",
                            Name = "Product 47",
                            Price = 891m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Product 48",
                            Name = "Product 48",
                            Price = 225m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Product 49",
                            Name = "Product 49",
                            Price = 909m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Product 50",
                            Name = "Product 50",
                            Price = 219m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Product 51",
                            Name = "Product 51",
                            Price = 976m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Product 52",
                            Name = "Product 52",
                            Price = 857m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Product 53",
                            Name = "Product 53",
                            Price = 330m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Product 54",
                            Name = "Product 54",
                            Price = 767m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Product 55",
                            Name = "Product 55",
                            Price = 513m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Product 56",
                            Name = "Product 56",
                            Price = 273m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Product 57",
                            Name = "Product 57",
                            Price = 875m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Product 58",
                            Name = "Product 58",
                            Price = 134m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Product 59",
                            Name = "Product 59",
                            Price = 403m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Product 60",
                            Name = "Product 60",
                            Price = 165m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Product 61",
                            Name = "Product 61",
                            Price = 830m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Product 62",
                            Name = "Product 62",
                            Price = 356m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Product 63",
                            Name = "Product 63",
                            Price = 439m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Product 64",
                            Name = "Product 64",
                            Price = 153m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Product 65",
                            Name = "Product 65",
                            Price = 905m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Product 66",
                            Name = "Product 66",
                            Price = 104m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Product 67",
                            Name = "Product 67",
                            Price = 948m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Product 68",
                            Name = "Product 68",
                            Price = 451m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Product 69",
                            Name = "Product 69",
                            Price = 651m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Product 70",
                            Name = "Product 70",
                            Price = 918m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Product 71",
                            Name = "Product 71",
                            Price = 355m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Product 72",
                            Name = "Product 72",
                            Price = 960m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Product 73",
                            Name = "Product 73",
                            Price = 402m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Product 74",
                            Name = "Product 74",
                            Price = 446m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Product 75",
                            Name = "Product 75",
                            Price = 913m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Product 76",
                            Name = "Product 76",
                            Price = 269m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Product 77",
                            Name = "Product 77",
                            Price = 738m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Product 78",
                            Name = "Product 78",
                            Price = 997m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Product 79",
                            Name = "Product 79",
                            Price = 368m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Product 80",
                            Name = "Product 80",
                            Price = 758m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Product 81",
                            Name = "Product 81",
                            Price = 439m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Product 82",
                            Name = "Product 82",
                            Price = 642m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Product 83",
                            Name = "Product 83",
                            Price = 429m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Product 84",
                            Name = "Product 84",
                            Price = 842m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Product 85",
                            Name = "Product 85",
                            Price = 155m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Product 86",
                            Name = "Product 86",
                            Price = 598m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Product 87",
                            Name = "Product 87",
                            Price = 354m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Product 88",
                            Name = "Product 88",
                            Price = 640m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Product 89",
                            Name = "Product 89",
                            Price = 610m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Product 90",
                            Name = "Product 90",
                            Price = 473m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Product 91",
                            Name = "Product 91",
                            Price = 584m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Product 92",
                            Name = "Product 92",
                            Price = 388m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Product 93",
                            Name = "Product 93",
                            Price = 385m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Product 94",
                            Name = "Product 94",
                            Price = 188m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Product 95",
                            Name = "Product 95",
                            Price = 512m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Product 96",
                            Name = "Product 96",
                            Price = 971m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Product 97",
                            Name = "Product 97",
                            Price = 889m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Product 98",
                            Name = "Product 98",
                            Price = 595m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Product 99",
                            Name = "Product 99",
                            Price = 959m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = "Product 100",
                            Name = "Product 100",
                            Price = 804m
                        });
                });

            modelBuilder.Entity("CatalogDomain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 4
                        });
                });

            modelBuilder.Entity("CatalogDomain.ProductInStock", b =>
                {
                    b.HasOne("CatalogDomain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("CatalogDomain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CatalogDomain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
